language: objective-c
osx_image: xcode61
rvm:
- 2.2
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: UnityProject/*
  skip_cleanup: true
  on:
    tags: true