language: objective-c
osx_image: xcode61
rvm:
- 2.1
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 006ff3a66d27b256f58bd5d11220f8e06f993ac0  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: deployment