language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

dist: trusty
sudo: required

env:
- TRAVIS_TAG="3.0" PROJECT_NAME="TestPackage" UNITY_PROJECT_PATH="UnityExample" UNITY_DOWNLOAD_CACHE="$(pwd)/unity_download_cache" DEPLOY_UNITYPACKAGE="path set in deploy script"

addons:
  sonarcloud:
    organization: "hoogendoornm-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- rvm get stable
- chmod a+x ./travis-build/*.sh

install:
- cat /etc/hosts
- ./travis-build/install-unity.sh

script:
- ./travis-build/build.sh
- sonar-scanner

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $(pwd)/Build/windows.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true 