language: generic
os: osx

install:
- sudo sh ./Scripts/install.sh
script:
- sudo sh ./Scripts/build.sh
after_success:
- sudo sh ./Scripts/post_build.sh

notifications:
  email:
    on_success: never
    on_failure: change

env:
  global:
    # environment variable for name of the Unity Project - rename this as needed
    - UNITY_PROJECT_NAME=UnityProject
    - UPLOAD_KEYFILE="./Scripts/upload"